# spring.application.name=backend

# spring.messages.basename=messages
# spring.messages.encoding=UTF-8
# spring.messages.cache-duration=3600
# spring.messages.fallback-to-system-locale=false

# spring.datasource.url=jdbc:postgresql://localhost:5432/ilhafit
# spring.datasource.username=postgres
# spring.datasource.password=root
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

spring.application.name=backend

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600
spring.messages.fallback-to-system-locale=false

spring.datasource.url=jdbc:mysql://localhost:3306/ilhafit?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true